// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoGe8YJBUXz11HtmjueYUptlHn9yLrvjE',
    appId: '1:832182128422:web:44712476c4492aa7053be7',
    messagingSenderId: '832182128422',
    projectId: 'fluttermart-6dc3f',
    authDomain: 'fluttermart-6dc3f.firebaseapp.com',
    storageBucket: 'fluttermart-6dc3f.appspot.com',
    measurementId: 'G-JT17Y46FB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeUwxMr9m8swXcZqLyUVVQRqIPM9wtT-k',
    appId: '1:832182128422:android:76bfe3d036b26708053be7',
    messagingSenderId: '832182128422',
    projectId: 'fluttermart-6dc3f',
    storageBucket: 'fluttermart-6dc3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAAQNiVgabUaf49dpNDjIzB3SQZ33bOp8',
    appId: '1:832182128422:ios:06ca4a4aef8dcc26053be7',
    messagingSenderId: '832182128422',
    projectId: 'fluttermart-6dc3f',
    storageBucket: 'fluttermart-6dc3f.appspot.com',
    iosBundleId: 'com.example.flutterMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAAQNiVgabUaf49dpNDjIzB3SQZ33bOp8',
    appId: '1:832182128422:ios:06ca4a4aef8dcc26053be7',
    messagingSenderId: '832182128422',
    projectId: 'fluttermart-6dc3f',
    storageBucket: 'fluttermart-6dc3f.appspot.com',
    iosBundleId: 'com.example.flutterMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoGe8YJBUXz11HtmjueYUptlHn9yLrvjE',
    appId: '1:832182128422:web:d219fd72a9b3a89d053be7',
    messagingSenderId: '832182128422',
    projectId: 'fluttermart-6dc3f',
    authDomain: 'fluttermart-6dc3f.firebaseapp.com',
    storageBucket: 'fluttermart-6dc3f.appspot.com',
    measurementId: 'G-ZCS8B4CGR2',
  );
}
